baseURL = "/koazee/"
languageCode = "en-us"
publishDir = "../docs"
title = "Koazee"
theme = "kube"
description = "Lazy like a koala, smart like a chimpanzee"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "newpixcom" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "ivan.corrales.solera@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
