baseURL = "http://wesovilabs.com/koazee/"
languageCode = "en-us"
publishDir = "../docs"
title = "Koazee"
theme = "kube"
description = "Lazy like a koala, smart like a chimpanzee"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "Iván Corrales Solera"
  github = "https://github.com/ivancorrales"
  twitter = "" # add your twitter profile
  email = "ivan.corrales.solera@gmail.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"
